export const BIBLE_BOOKS = [
    // --- Old Testament (39 Books) ---
    { id: 'Genesis', name: 'Genesis', teluguName: 'ఆదికాండము', file: 'Gdata', testament: 'OT', chapters: 50 },
    { id: 'Exodus', name: 'Exodus', teluguName: 'నిర్గమకాండము', file: 'Edata', testament: 'OT', chapters: 40 },
    { id: 'Leviticus', name: 'Leviticus', teluguName: 'లేవీయకాండము', file: 'Ldata', testament: 'OT', chapters: 27 },
    { id: 'Numbers', name: 'Numbers', teluguName: 'సంఖ్యాకాండము', file: 'Ndata', testament: 'OT', chapters: 36 },
    { id: 'Deuteronomy', name: 'Deuteronomy', teluguName: 'ద్వితీయోపదేశకాండము', file: 'Ddata', testament: 'OT', chapters: 34 },
    { id: 'Joshua', name: 'Joshua', teluguName: 'యెహోషువ', file: 'Joshdata', testament: 'OT', chapters: 24 },
    { id: 'Judges', name: 'Judges', teluguName: 'న్యాయాధిపతులు', file: 'Judgdata', testament: 'OT', chapters: 21 },
    { id: 'Ruth', name: 'Ruth', teluguName: 'రూతు', file: 'Ruthdata', testament: 'OT', chapters: 4 },
    { id: '1Samuel', name: '1 Samuel', teluguName: '1 సమూయేలు', file: '1Samdata', testament: 'OT', chapters: 31 },
    { id: '2Samuel', name: '2 Samuel', teluguName: '2 సమూయేలు', file: '2Samdata', testament: 'OT', chapters: 24 },
    { id: '1Kings', name: '1 Kings', teluguName: '1 రాజులు', file: '1Kingsdata', testament: 'OT', chapters: 22 },
    { id: '2Kings', name: '2 Kings', teluguName: '2 రాజులు', file: '2Kingsdata', testament: 'OT', chapters: 25 },
    { id: '1Chronicles', name: '1 Chronicles', teluguName: '1 దినవృత్తాంతములు', file: '1Chrdata', testament: 'OT', chapters: 29 },
    { id: '2Chronicles', name: '2 Chronicles', teluguName: '2 దినవృత్తాంతములు', file: '2Chrdata', testament: 'OT', chapters: 36 },
    { id: 'Ezra', name: 'Ezra', teluguName: 'ఎజ్రా', file: 'Ezradata', testament: 'OT', chapters: 10 },
    { id: 'Nehemiah', name: 'Nehemiah', teluguName: 'నెహెమ్యా', file: 'Nehdata', testament: 'OT', chapters: 13 },
    { id: 'Esther', name: 'Esther', teluguName: 'ఎస్తేరు', file: 'Estherdata', testament: 'OT', chapters: 10 },
    { id: 'Job', name: 'Job', teluguName: 'యోబు', file: 'Jobdata', testament: 'OT', chapters: 42 },
    { id: 'Psalms', name: 'Psalms', teluguName: 'కీర్తనలు', file: 'Psalmsdata', testament: 'OT', chapters: 150 },
    { id: 'Proverbs', name: 'Proverbs', teluguName: 'సామెతలు', file: 'Proverbsdata', testament: 'OT', chapters: 31 },
    { id: 'Ecclesiastes', name: 'Ecclesiastes', teluguName: 'ప్రసంగి', file: 'Ecclesiastesdata', testament: 'OT', chapters: 12 },
    { id: 'SongofSolomon', name: 'Song of Solomon', teluguName: 'పరమగీతము', file: 'SongofSolomondata', testament: 'OT', chapters: 8 },
    { id: 'Isaiah', name: 'Isaiah', teluguName: 'యెషయా', file: 'Isaiahdata', testament: 'OT', chapters: 66 },
    { id: 'Jeremiah', name: 'Jeremiah', teluguName: 'యిర్మీయా', file: 'Jeremiahdata', testament: 'OT', chapters: 52 },
    { id: 'Lamentations', name: 'Lamentations', teluguName: 'విలాపవాక్యములు', file: 'Lamentationsdata', testament: 'OT', chapters: 5 },
    { id: 'Ezekiel', name: 'Ezekiel', teluguName: 'యెహెజ్కేలు', file: 'Ezekieldata', testament: 'OT', chapters: 48 },
    { id: 'Daniel', name: 'Daniel', teluguName: 'దానియేలు', file: 'Danieldata', testament: 'OT', chapters: 14 },
    { id: 'Hosea', name: 'Hosea', teluguName: 'హోషేయ', file: 'Hoseadata', testament: 'OT', chapters: 14 },
    { id: 'Joel', name: 'Joel', teluguName: 'యోవేలు', file: 'Joeldata', testament: 'OT', chapters: 3 },
    { id: 'Amos', name: 'Amos', teluguName: 'ఆమోసు', file: 'Amosdata', testament: 'OT', chapters: 9 },
    { id: 'Obadiah', name: 'Obadiah', teluguName: 'ఓబద్యా', file: 'Obadiahdata', testament: 'OT', chapters: 1 },
    { id: 'Jonah', name: 'Jonah', teluguName: 'యోనా', file: 'Jonahdata', testament: 'OT', chapters: 4 },
    { id: 'Micah', name: 'Micah', teluguName: 'మీకా', file: 'Micahdata', testament: 'OT', chapters: 7 },
    { id: 'Nahum', name: 'Nahum', teluguName: 'నహూము', file: 'Nahumdata', testament: 'OT', chapters: 3 },
    { id: 'Habakkuk', name: 'Habakkuk', teluguName: 'హబక్కూకు', file: 'Habakkukdata', testament: 'OT', chapters: 3 },
    { id: 'Zephaniah', name: 'Zephaniah', teluguName: 'జెఫన్యా', file: 'Zephaniahdata', testament: 'OT', chapters: 3 },
    { id: 'Haggai', name: 'Haggai', teluguName: 'హగ్గయి', file: 'Haggaidata', testament: 'OT', chapters: 2 },
    { id: 'Zechariah', name: 'Zechariah', teluguName: 'జెకర్యా', file: 'Zechariahdata', testament: 'OT', chapters: 14 },
    { id: 'Malachi', name: 'Malachi', teluguName: 'మలాకీ', file: 'Malachidata', testament: 'OT', chapters: 4 },

    // --- New Testament (27 Books) ---
    { id: 'Matthew', name: 'Matthew', teluguName: 'మత్తయి', file: 'Matthewdata', testament: 'NT', chapters: 28 },
    { id: 'Mark', name: 'Mark', teluguName: 'మార్కు', file: 'Markdata', testament: 'NT', chapters: 16 },
    { id: 'Luke', name: 'Luke', teluguName: 'లూకా', file: 'Lukedata', testament: 'NT', chapters: 24 },
    { id: 'John', name: 'John', teluguName: 'యోహాను', file: 'Johndata', testament: 'NT', chapters: 21 },
    { id: 'Acts', name: 'Acts', teluguName: 'అపొస్తలుల కార్యములు', file: 'Actsdata', testament: 'NT', chapters: 28 },
    { id: 'Romans', name: 'Romans', teluguName: 'రోమీయులకు', file: 'Romansdata', testament: 'NT', chapters: 16 },
    { id: '1Corinthians', name: '1 Corinthians', teluguName: '1 కొరింథీయులకు', file: '1Corinthiansdata', testament: 'NT', chapters: 16 },
    { id: '2Corinthians', name: '2 Corinthians', teluguName: '2 కొరింథీయులకు', file: '2Corinthiansdata', testament: 'NT', chapters: 13 },
    { id: 'Galatians', name: 'Galatians', teluguName: 'గలతీయులకు', file: 'Galatiansdata', testament: 'NT', chapters: 6 },
    { id: 'Ephesians', name: 'Ephesians', teluguName: 'ఎఫెసీయులకు', file: 'Ephesiansdata', testament: 'NT', chapters: 6 },
    { id: 'Philippians', name: 'Philippians', teluguName: 'ఫిలిప్పీయులకు', file: 'Philippiansdata', testament: 'NT', chapters: 4 },
    { id: 'Colossians', name: 'Colossians', teluguName: 'కొలొస్సయులకు', file: 'Colossiansdata', testament: 'NT', chapters: 4 },
    { id: '1Thessalonians', name: '1 Thessalonians', teluguName: '1 థెస్సలొనీకయులకు', file: '1Thessaloniansdata', testament: 'NT', chapters: 5 },
    { id: '2Thessalonians', name: '2 Thessalonians', teluguName: '2 థెస్సలొనీకయులకు', file: '2Thessaloniansdata', testament: 'NT', chapters: 3 },
    { id: '1Timothy', name: '1 Timothy', teluguName: '1 తిమోతికి', file: '1Timothydata', testament: 'NT', chapters: 6 },
    { id: '2Timothy', name: '2 Timothy', teluguName: '2 తిమోతికి', file: '2Timothydata', testament: 'NT', chapters: 4 },
    { id: 'Titus', name: 'Titus', teluguName: 'తీతుకు', file: 'Titusdata', testament: 'NT', chapters: 3 },
    { id: 'Philemon', name: 'Philemon', teluguName: 'ఫిలేమోనుకు', file: 'Philemondata', testament: 'NT', chapters: 1 },
    { id: 'Hebrews', name: 'Hebrews', teluguName: 'హెబ్రీయులకు', file: 'Hebrewsdata', testament: 'NT', chapters: 13 },
    { id: 'James', name: 'James', teluguName: 'యాకోబు', file: 'Jamesdata', testament: 'NT', chapters: 5 },
    { id: '1Peter', name: '1 Peter', teluguName: '1 పేతురు', file: '1Peterdata', testament: 'NT', chapters: 5 },
    { id: '2Peter', name: '2 Peter', teluguName: '2 పేతురు', file: '2Peterdata', testament: 'NT', chapters: 3 },
    { id: '1John', name: '1 John', teluguName: '1 యోహాను', file: '1Johndata', testament: 'NT', chapters: 5 },
    { id: '2John', name: '2 John', teluguName: '2 యోహాను', file: '2Johndata', testament: 'NT', chapters: 1 },
    { id: '3John', name: '3 John', teluguName: '3 యోహాను', file: '3Johndata', testament: 'NT', chapters: 1 },
    { id: 'Jude', name: 'Jude', teluguName: 'యూదా', file: 'Judedata', testament: 'NT', chapters: 1 },
    { id: 'Revelation', name: 'Revelation', teluguName: 'ప్రకటన గ్రంథము', file: 'Revelationdata', testament: 'NT', chapters: 22 },
];

export const TOTAL_BIBLE_CHAPTERS = BIBLE_BOOKS.reduce((acc, b) => acc + b.chapters, 0); // 1189
export const TOTAL_OT_CHAPTERS = BIBLE_BOOKS.filter(b => b.testament === 'OT').reduce((acc, b) => acc + b.chapters, 0); // 929
export const TOTAL_NT_CHAPTERS = BIBLE_BOOKS.filter(b => b.testament === 'NT').reduce((acc, b) => acc + b.chapters, 0); // 260
export const TOTAL_OT_BOOKS = 39;
export const TOTAL_NT_BOOKS = 27;
export const TOTAL_BIBLE_BOOKS = 66;
